spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/admin/users/**
        - id: request-service
          uri: lb://request-service
          predicates:
            - Path=/users/**
        - id: location-service-admin
          uri: lb://location-service
          predicates:
            - Path=/admin/location/**
        - id: location-service-public
          uri: lb://location-service
          predicates:
            - Path=/public/location/**
        - id: event-service
          uri: lb://event-service
          predicates:
            - Path=/events/**

server:
  port: 8080

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG